package com.fly.sync.mysql.model;

import com.fly.sync.contract.ModelInterface;

import java.beans.ConstructorProperties;

public class Column implements ModelInterface {

    public String TABLE_CATALOG;
    public String TABLE_SCHEMA;
    public String TABLE_NAME;
    public String COLUMN_NAME;
    public long ORDINAL_POSITION;
    public String COLUMN_DEFAULT;
    public String IS_NULLABLE;
    public String DATA_TYPE;
    public long CHARACTER_MAXIMUM_LENGTH;
    public long CHARACTER_OCTET_LENGTH;
    public long NUMERIC_PRECISION;
    public long NUMERIC_SCALE;
    public long DATETIME_PRECISION;
    public String CHARACTER_SET_NAME;
    public String COLLATION_NAME;
    public String COLUMN_TYPE;
    public String COLUMN_KEY;
    public String EXTRA;
    public String PRIVILEGES;
    public String COLUMN_COMMENT;
    public String GENERATION_EXPRESSION;

    @ConstructorProperties({"TABLE_CATALOG", "TABLE_SCHEMA", "TABLE_NAME", "COLUMN_NAME", "ORDINAL_POSITION", "COLUMN_DEFAULT", "IS_NULLABLE", "DATA_TYPE", "CHARACTER_MAXIMUM_LENGTH", "CHARACTER_OCTET_LENGTH", "NUMERIC_PRECISION", "NUMERIC_SCALE", "DATETIME_PRECISION", "CHARACTER_SET_NAME", "COLLATION_NAME", "COLUMN_TYPE", "COLUMN_KEY", "EXTRA", "PRIVILEGES", "COLUMN_COMMENT", "GENERATION_EXPRESSION"})
    public Column(String TABLE_CATALOG, String TABLE_SCHEMA, String TABLE_NAME, String COLUMN_NAME, long ORDINAL_POSITION, String COLUMN_DEFAULT, String IS_NULLABLE, String DATA_TYPE, long CHARACTER_MAXIMUM_LENGTH, long CHARACTER_OCTET_LENGTH, long NUMERIC_PRECISION, long NUMERIC_SCALE, long DATETIME_PRECISION, String CHARACTER_SET_NAME, String COLLATION_NAME, String COLUMN_TYPE, String COLUMN_KEY, String EXTRA, String PRIVILEGES, String COLUMN_COMMENT, String GENERATION_EXPRESSION) {
        this.TABLE_CATALOG = TABLE_CATALOG;
        this.TABLE_SCHEMA = TABLE_SCHEMA;
        this.TABLE_NAME = TABLE_NAME;
        this.COLUMN_NAME = COLUMN_NAME;
        this.ORDINAL_POSITION = ORDINAL_POSITION;
        this.COLUMN_DEFAULT = COLUMN_DEFAULT;
        this.IS_NULLABLE = IS_NULLABLE;
        this.DATA_TYPE = DATA_TYPE;
        this.CHARACTER_MAXIMUM_LENGTH = CHARACTER_MAXIMUM_LENGTH;
        this.CHARACTER_OCTET_LENGTH = CHARACTER_OCTET_LENGTH;
        this.NUMERIC_PRECISION = NUMERIC_PRECISION;
        this.NUMERIC_SCALE = NUMERIC_SCALE;
        this.DATETIME_PRECISION = DATETIME_PRECISION;
        this.CHARACTER_SET_NAME = CHARACTER_SET_NAME;
        this.COLLATION_NAME = COLLATION_NAME;
        this.COLUMN_TYPE = COLUMN_TYPE;
        this.COLUMN_KEY = COLUMN_KEY;
        this.EXTRA = EXTRA;
        this.PRIVILEGES = PRIVILEGES;
        this.COLUMN_COMMENT = COLUMN_COMMENT;
        this.GENERATION_EXPRESSION = GENERATION_EXPRESSION;
    }
}
